version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1@Shashikant
      MYSQL_DATABASE: consma
    ports:
      - "3307:3306"
    networks:
      - scm-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: smartcontactmanager-pipeline-app
    container_name: smart-contact-manager
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/consma
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1@Shashikant
    depends_on:
      - mysql
    ports:
      - "8085:8080"
    networks:
      - scm-network

  nagios:
    image: jasonrivers/nagios
    container_name: nagios
    ports:
      - "9081:80"
    volumes:
      - ./nagios/etc:/opt/nagios/etc
      - ./nagios/var:/opt/nagios/var
    networks:
      - scm-network
    depends_on:
      - mysql
      - app

networks:
  scm-network:

volumes:
  mysql-data:
